### ISSUE TITLE
sh files not executable after downloading

### ISSUE THREAD

**Issue by Danfro** [nicolascolla/comfy-keyboard#2]
Here after downloading to my laptop, the sh files where not executable. I needed to run `chmod +x ./run_focal.sh` to make it work. Maybe add that to the readme? Or did I do something wrong?

**Comment by nicolascolla** [comment]
Hi Danfro,

Could you describe to me the method you used to get the files into the device so I can try to replicate it? Personally, if I git clone the repository, the four scripts are executable:

![](https://i.imgur.com/RBHn5ZX.png)

Same when downloading and uncompressing the zip directly:

![](https://i.imgur.com/FsyIEuE.png)

Now that I'm thinking I should probably add to the README a way to download the files.

**Comment by Danfro** [comment]
I did download the files as zip on my laptop, extract there and then copy via usb cable to my phone. Even when making them executable on my Ubuntu laptop, when copying (I actually did cut&paste I think), they became not executable.

--

**Comment by nicolascolla** [comment]
Since I can think of a myriad of ways in which the files could become non-executable (for example, like you say, when being transferred), I think it's better to update the documentation to, instead of running the scripts directly, call bash with the script as an argument.
